import { pgTable, text, timestamp, boolean, uuid, varchar, pgEnum, index } from "drizzle-orm/pg-core"
import { relations } from "drizzle-orm"

// ─────────────────────────────────────────────────────────────────────────────
// BETTER AUTH TABLES (Generated by bunx auth generate)
// ─────────────────────────────────────────────────────────────────────────────

export const user = pgTable("user", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  emailVerified: boolean("email_verified").default(false).notNull(),
  image: text("image"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at")
    .defaultNow()
    .$onUpdate(() => new Date())
    .notNull(),
  username: text("username").unique(),
  displayUsername: text("display_username"),
  role: text("role"),
  banned: boolean("banned").default(false),
  banReason: text("ban_reason"),
  banExpires: timestamp("ban_expires"),
  phone: text("phone"),
})

export const session = pgTable(
  "session",
  {
    id: text("id").primaryKey(),
    expiresAt: timestamp("expires_at").notNull(),
    token: text("token").notNull().unique(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .$onUpdate(() => new Date())
      .notNull(),
    ipAddress: text("ip_address"),
    userAgent: text("user_agent"),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    activeOrganizationId: text("active_organization_id"),
    impersonatedBy: text("impersonated_by"),
  },
  (table) => [index("session_userId_idx").on(table.userId)],
)

export const account = pgTable(
  "account",
  {
    id: text("id").primaryKey(),
    accountId: text("account_id").notNull(),
    providerId: text("provider_id").notNull(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    accessToken: text("access_token"),
    refreshToken: text("refresh_token"),
    idToken: text("id_token"),
    accessTokenExpiresAt: timestamp("access_token_expires_at"),
    refreshTokenExpiresAt: timestamp("refresh_token_expires_at"),
    scope: text("scope"),
    password: text("password"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (table) => [index("account_userId_idx").on(table.userId)],
)

export const verification = pgTable(
  "verification",
  {
    id: text("id").primaryKey(),
    identifier: text("identifier").notNull(),
    value: text("value").notNull(),
    expiresAt: timestamp("expires_at").notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .defaultNow()
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (table) => [index("verification_identifier_idx").on(table.identifier)],
)

export const organization = pgTable("organization", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  slug: text("slug").notNull().unique(),
  logo: text("logo"),
  createdAt: timestamp("created_at").notNull(),
  metadata: text("metadata"),
})

export const member = pgTable(
  "member",
  {
    id: text("id").primaryKey(),
    organizationId: text("organization_id")
      .notNull()
      .references(() => organization.id, { onDelete: "cascade" }),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    role: text("role").default("member").notNull(),
    createdAt: timestamp("created_at").notNull(),
  },
  (table) => [
    index("member_organizationId_idx").on(table.organizationId),
    index("member_userId_idx").on(table.userId),
  ],
)

export const invitation = pgTable(
  "invitation",
  {
    id: text("id").primaryKey(),
    organizationId: text("organization_id")
      .notNull()
      .references(() => organization.id, { onDelete: "cascade" }),
    email: text("email").notNull(),
    role: text("role"),
    status: text("status").default("pending").notNull(),
    expiresAt: timestamp("expires_at").notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    inviterId: text("inviter_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
  },
  (table) => [
    index("invitation_organizationId_idx").on(table.organizationId),
    index("invitation_email_idx").on(table.email),
  ],
)

// ─────────────────────────────────────────────────────────────────────────────
// AUTH RELATIONS
// ─────────────────────────────────────────────────────────────────────────────

export const userRelations = relations(user, ({ many }) => ({
  sessions: many(session),
  accounts: many(account),
  members: many(member),
  invitations: many(invitation),
}))

export const sessionRelations = relations(session, ({ one }) => ({
  user: one(user, {
    fields: [session.userId],
    references: [user.id],
  }),
}))

export const accountRelations = relations(account, ({ one }) => ({
  user: one(user, {
    fields: [account.userId],
    references: [user.id],
  }),
}))

export const organizationRelations = relations(organization, ({ many }) => ({
  members: many(member),
  invitations: many(invitation),
  // TMS tables
  loads: many(load),
  drivers: many(driver),
  trucks: many(truck),
  trailers: many(trailer),
  invoices: many(invoice),
  trips: many(trip),
  carrierPayments: many(carrierPayment),
  apExpenses: many(apExpense),
  payStubs: many(payStub),
}))

export const memberRelations = relations(member, ({ one }) => ({
  organization: one(organization, {
    fields: [member.organizationId],
    references: [organization.id],
  }),
  user: one(user, {
    fields: [member.userId],
    references: [user.id],
  }),
}))

export const invitationRelations = relations(invitation, ({ one }) => ({
  organization: one(organization, {
    fields: [invitation.organizationId],
    references: [organization.id],
  }),
  inviter: one(user, {
    fields: [invitation.inviterId],
    references: [user.id],
  }),
}))

// ─────────────────────────────────────────────────────────────────────────────
// TMS TABLES (Your business data - all with tenantId for multi-tenancy)
// ─────────────────────────────────────────────────────────────────────────────

// Enum for load status
export const loadStatusEnum = pgEnum("load_status", [
  "available",
  "booked",
  "dispatched",
  "in_transit",
  "delivered",
  "completed",
  "cancelled",
])

// Loads table (freight/shipments)
export const load = pgTable("load", {
  id: text("id").primaryKey(),
  tenantId: text("tenant_id")
    .notNull()
    .references(() => organization.id, { onDelete: "cascade" }),
  loadNumber: varchar("load_number", { length: 50 }).notNull(),
  status: loadStatusEnum("status").notNull().default("available"),

  // Customer info
  customerId: text("customer_id"),
  customerName: varchar("customer_name", { length: 255 }),
  customerEmail: varchar("customer_email", { length: 255 }),

  // Origin
  originAddress: text("origin_address"),
  originCity: varchar("origin_city", { length: 100 }),
  originState: varchar("origin_state", { length: 50 }),
  originZip: varchar("origin_zip", { length: 20 }),
  originContact: varchar("origin_contact", { length: 100 }),
  originPhone: varchar("origin_phone", { length: 50 }),
  originAppointment: timestamp("origin_appointment"),

  // Destination
  destAddress: text("dest_address"),
  destCity: varchar("dest_city", { length: 100 }),
  destState: varchar("dest_state", { length: 50 }),
  destZip: varchar("dest_zip", { length: 20 }),
  destContact: varchar("dest_contact", { length: 100 }),
  destPhone: varchar("dest_phone", { length: 50 }),
  destAppointment: timestamp("dest_appointment"),

  // Load details
  loadType: varchar("load_type", { length: 50 }), // van, reefer, flatbed
  commodity: varchar("commodity", { length: 255 }),
  weight: varchar("weight", { length: 50 }),
  rate: varchar("rate", { length: 50 }), // Revenue rate
  customerRate: varchar("customer_rate", { length: 50 }),
  carrierRate: varchar("carrier_rate", { length: 50 }),
  miles: varchar("miles", { length: 50 }),
  deadhead: varchar("deadhead", { length: 50 }),

  // Profit tracking
  targetProfit: varchar("target_profit", { length: 50 }),
  actualProfit: varchar("actual_profit", { length: 50 }),

  // BOL tracking
  bolNumber: varchar("bol_number", { length: 50 }),
  bolReceived: boolean("bol_received").default(false),
  podSigned: boolean("pod_signed").default(false),

  // Rate confirmation
  rateConfirmNumber: varchar("rate_confirm_number", { length: 50 }),
  rateConfirmed: boolean("rate_confirmed").default(false),

  // Timestamps
  pickupDate: timestamp("pickup_date"),
  deliveryDate: timestamp("delivery_date"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
})

// Trips table (load runs)
export const trip = pgTable("trip", {
  id: text("id").primaryKey(),
  tenantId: text("tenant_id")
    .notNull()
    .references(() => organization.id, { onDelete: "cascade" }),
  tripNumber: varchar("trip_number", { length: 50 }).notNull(),
  loadId: text("load_id").references(() => load.id),
  driverId: text("driver_id").references(() => driver.id),
  truckId: text("truck_id").references(() => truck.id),
  trailerId: text("trailer_id").references(() => trailer.id),
  status: varchar("status", { length: 50 }).notNull().default("pending"),
  startDate: timestamp("start_date"),
  endDate: timestamp("end_date"),
  totalMiles: varchar("total_miles", { length: 50 }),
  totalRevenue: varchar("total_revenue", { length: 50 }),
  totalExpense: varchar("total_expense", { length: 50 }),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
})

// Drivers table
export const driver = pgTable("driver", {
  id: text("id").primaryKey(),
  tenantId: text("tenant_id")
    .notNull()
    .references(() => organization.id, { onDelete: "cascade" }),
  userId: text("user_id").references(() => user.id),
  firstName: varchar("first_name", { length: 100 }).notNull(),
  lastName: varchar("last_name", { length: 100 }).notNull(),
  email: varchar("email", { length: 255 }),
  phone: varchar("phone", { length: 50 }),
  cdlNumber: varchar("cdl_number", { length: 50 }),
  cdlState: varchar("cdl_state", { length: 50 }),
  cdlExpiration: timestamp("cdl_expiration"),
  dateOfBirth: timestamp("date_of_birth"),
  address: text("address"),
  city: varchar("city", { length: 100 }),
  state: varchar("state", { length: 50 }),
  zip: varchar("zip", { length: 20 }),
  status: varchar("status", { length: 50 }).notNull().default("active"),
  hireDate: timestamp("hire_date"),
  payRate: varchar("pay_rate", { length: 50 }),
  payType: varchar("pay_type", { length: 50 }),
  emergencyContact: varchar("emergency_contact", { length: 100 }),
  emergencyPhone: varchar("emergency_phone", { length: 50 }),
  notes: text("notes"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
})

// Trucks table
export const truck = pgTable("truck", {
  id: text("id").primaryKey(),
  tenantId: text("tenant_id")
    .notNull()
    .references(() => organization.id, { onDelete: "cascade" }),
  unitNumber: varchar("unit_number", { length: 50 }).notNull(),
  make: varchar("make", { length: 100 }),
  model: varchar("model", { length: 100 }),
  year: varchar("year", { length: 10 }),
  vin: varchar("vin", { length: 50 }),
  licensePlate: varchar("license_plate", { length: 50 }),
  licenseState: varchar("license_state", { length: 50 }),
  licenseExpiration: timestamp("license_expiration"),
  fuelType: varchar("fuel_type", { length: 50 }),
  fuelCapacity: varchar("fuel_capacity", { length: 50 }),
  status: varchar("status", { length: 50 }).notNull().default("available"),
  currentLocation: varchar("current_location", { length: 255 }),
  currentMiles: varchar("current_miles", { length: 50 }),
  nextServiceMiles: varchar("next_service_miles", { length: 50 }),
  nextServiceDate: timestamp("next_service_date"),
  notes: text("notes"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
})

// Trailers table
export const trailer = pgTable("trailer", {
  id: text("id").primaryKey(),
  tenantId: text("tenant_id")
    .notNull()
    .references(() => organization.id, { onDelete: "cascade" }),
  unitNumber: varchar("unit_number", { length: 50 }).notNull(),
  type: varchar("type", { length: 50 }),
  make: varchar("make", { length: 100 }),
  model: varchar("model", { length: 100 }),
  year: varchar("year", { length: 10 }),
  vin: varchar("vin", { length: 50 }),
  licensePlate: varchar("license_plate", { length: 50 }),
  licenseState: varchar("license_state", { length: 50 }),
  licenseExpiration: timestamp("license_expiration"),
  status: varchar("status", { length: 50 }).notNull().default("available"),
  currentLocation: varchar("current_location", { length: 255 }),
  length: varchar("length", { length: 50 }),
  capacity: varchar("capacity", { length: 50 }),
  notes: text("notes"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
})

// Invoices table
export const invoice = pgTable("invoice", {
  id: text("id").primaryKey(),
  tenantId: text("tenant_id")
    .notNull()
    .references(() => organization.id, { onDelete: "cascade" }),
  invoiceNumber: varchar("invoice_number", { length: 50 }).notNull(),
  loadId: text("load_id").references(() => load.id),
  customerId: text("customer_id"),
  customerName: varchar("customer_name", { length: 255 }),
  customerEmail: varchar("customer_email", { length: 255 }),
  amount: varchar("amount", { length: 50 }).notNull(),
  status: varchar("status", { length: 50 }).notNull().default("pending"),
  dueDate: timestamp("due_date"),
  paidDate: timestamp("paid_date"),
  notes: text("notes"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
})

// Carrier payments table
export const carrierPayment = pgTable("carrier_payment", {
  id: text("id").primaryKey(),
  tenantId: text("tenant_id")
    .notNull()
    .references(() => organization.id, { onDelete: "cascade" }),
  tripId: text("trip_id").references(() => trip.id),
  driverId: text("driver_id").references(() => driver.id),
  amount: varchar("amount", { length: 50 }).notNull(),
  status: varchar("status", { length: 50 }).notNull().default("pending"),
  paymentDate: timestamp("payment_date"),
  paymentMethod: varchar("payment_method", { length: 50 }),
  notes: text("notes"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
})

// AP Expenses table
export const apExpense = pgTable("ap_expense", {
  id: text("id").primaryKey(),
  tenantId: text("tenant_id")
    .notNull()
    .references(() => organization.id, { onDelete: "cascade" }),
  tripId: text("trip_id").references(() => trip.id),
  driverId: text("driver_id").references(() => driver.id),
  type: varchar("type", { length: 100 }).notNull(),
  vendor: varchar("vendor", { length: 255 }),
  amount: varchar("amount", { length: 50 }).notNull(),
  date: timestamp("date").notNull(),
  status: varchar("status", { length: 50 }).notNull().default("pending"),
  notes: text("notes"),
  receipt: text("receipt"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
})

// Pay stubs table
export const payStub = pgTable("pay_stub", {
  id: text("id").primaryKey(),
  tenantId: text("tenant_id")
    .notNull()
    .references(() => organization.id, { onDelete: "cascade" }),
  driverId: text("driver_id")
    .notNull()
    .references(() => driver.id),
  payPeriodStart: timestamp("pay_period_start").notNull(),
  payPeriodEnd: timestamp("pay_period_end").notNull(),
  totalMiles: varchar("total_miles", { length: 50 }),
  payRate: varchar("pay_rate", { length: 50 }),
  grossPay: varchar("gross_pay", { length: 50 }).notNull(),
  deductions: varchar("deductions", { length: 50 }),
  netPay: varchar("net_pay", { length: 50 }).notNull(),
  status: varchar("status", { length: 50 }).notNull().default("pending"),
  paidDate: timestamp("paid_date"),
  notes: text("notes"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
})

// Pay items table (line items for pay stubs)
export const payItem = pgTable("pay_item", {
  id: text("id").primaryKey(),
  tenantId: text("tenant_id")
    .notNull()
    .references(() => organization.id, { onDelete: "cascade" }),
  payStubId: text("pay_stub_id")
    .notNull()
    .references(() => payStub.id),
  tripId: text("trip_id").references(() => trip.id),
  type: varchar("type", { length: 100 }).notNull(),
  description: varchar("description", { length: 255 }),
  quantity: varchar("quantity", { length: 50 }),
  rate: varchar("rate", { length: 50 }),
  amount: varchar("amount", { length: 50 }).notNull(),
  createdAt: timestamp("created_at").notNull().defaultNow(),
})

// ─────────────────────────────────────────────────────────────────────────────
// TMS RELATIONS
// ─────────────────────────────────────────────────────────────────────────────

export const loadRelations = relations(load, ({ one, many }) => ({
  organization: one(organization, {
    fields: [load.tenantId],
    references: [organization.id],
  }),
  trips: many(trip),
  invoices: many(invoice),
}))

export const tripRelations = relations(trip, ({ one, many }) => ({
  organization: one(organization, {
    fields: [trip.tenantId],
    references: [organization.id],
  }),
  load: one(load, {
    fields: [trip.loadId],
    references: [load.id],
  }),
  driver: one(driver, {
    fields: [trip.driverId],
    references: [driver.id],
  }),
  truck: one(truck, {
    fields: [trip.truckId],
    references: [truck.id],
  }),
  trailer: one(trailer, {
    fields: [trip.trailerId],
    references: [trailer.id],
  }),
  payItems: many(payItem),
  apExpenses: many(apExpense),
  carrierPayments: many(carrierPayment),
}))

export const driverRelations = relations(driver, ({ one, many }) => ({
  organization: one(organization, {
    fields: [driver.tenantId],
    references: [organization.id],
  }),
  user: one(user, {
    fields: [driver.userId],
    references: [user.id],
  }),
  trips: many(trip),
  payStubs: many(payStub),
  apExpenses: many(apExpense),
  carrierPayments: many(carrierPayment),
}))

export const truckRelations = relations(truck, ({ one, many }) => ({
  organization: one(organization, {
    fields: [truck.tenantId],
    references: [organization.id],
  }),
  trips: many(trip),
}))

export const trailerRelations = relations(trailer, ({ one, many }) => ({
  organization: one(organization, {
    fields: [trailer.tenantId],
    references: [organization.id],
  }),
  trips: many(trip),
}))

export const invoiceRelations = relations(invoice, ({ one }) => ({
  organization: one(organization, {
    fields: [invoice.tenantId],
    references: [organization.id],
  }),
  load: one(load, {
    fields: [invoice.loadId],
    references: [load.id],
  }),
}))

export const payStubRelations = relations(payStub, ({ one, many }) => ({
  organization: one(organization, {
    fields: [payStub.tenantId],
    references: [organization.id],
  }),
  driver: one(driver, {
    fields: [payStub.driverId],
    references: [driver.id],
  }),
  items: many(payItem),
}))

export const payItemRelations = relations(payItem, ({ one }) => ({
  organization: one(organization, {
    fields: [payItem.tenantId],
    references: [organization.id],
  }),
  payStub: one(payStub, {
    fields: [payItem.payStubId],
    references: [payStub.id],
  }),
  trip: one(trip, {
    fields: [payItem.tripId],
    references: [trip.id],
  }),
}))

export const carrierPaymentRelations = relations(carrierPayment, ({ one }) => ({
  organization: one(organization, {
    fields: [carrierPayment.tenantId],
    references: [organization.id],
  }),
  trip: one(trip, {
    fields: [carrierPayment.tripId],
    references: [trip.id],
  }),
  driver: one(driver, {
    fields: [carrierPayment.driverId],
    references: [driver.id],
  }),
}))

export const apExpenseRelations = relations(apExpense, ({ one }) => ({
  organization: one(organization, {
    fields: [apExpense.tenantId],
    references: [organization.id],
  }),
  trip: one(trip, {
    fields: [apExpense.tripId],
    references: [trip.id],
  }),
  driver: one(driver, {
    fields: [apExpense.driverId],
    references: [driver.id],
  }),
}))
